version: "3.8"

services:
  heimdall:
    container_name: heimdall
    image: ghcr.io/linuxserver/heimdall
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ${CONFIG_PATH}/heimdall/config:/config
    ports:
      - $HEIMDALL_HTTP_PORT}:80
      - ${HEIMDALL_HTTPS_PORT}:443