version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Rome
      - WEBPASSWORD=${PIHOLE_PASSWORD}
      - DNS1=8.8.8.8
      - DNS2=8.8.4.4
      - DNSSEC=true
    volumes:
      - /home/pi/pihole/data:/etc/pihole/
      - /home/pi/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    ports:
      - 53:53/tcp
      - 53:53/udp
      - ${PIHOLE_PORT}:80
    cap_add:
      - NET_ADMIN